const MEETINGS_DATA = [
  {
    id: 1,
    title: "10 May Meeting",
    description: "Time: 08:10",
    agenda: [
      "Marketing Strategy",
      "Sales Target",
      "Review Production Date",
      "Execute Project Prometheus",
      "Marketing Strategy",
      "Sales Target",
      "Review Production Date",
      "Execute Project Prometheus",
      "Marketing Strategy",
      "Sales Target",
      "Review Production Date",
      "Execute Project Prometheus",
    ],
    transcript: [
      "KarAik: I am so cool",
      "Rickson: Im cooler",
      "Hector: I'm the coolest",
      "KarAik: Chill Chill",
      "KarAik: I am so cool",
      "Rickson: Im cooler",
      "Hector: I'm the coolest",
      "KarAik: Chill Chill",
      "KarAik: I am so cool",
      "Rickson: Im cooler",
      "Hector: I'm the coolest",
      "KarAik: Chill Chill",
      "KarAik: I am so cool",
      "Rickson: Im cooler",
      "Hector: I'm the coolest",
      "KarAik: Chill Chill",
    ],
  },
  {
    id: 2,
    title: "11 May Meeting",
    description: "Time: 07:10",
  },
  {
    id: 3,
    title: "12 May Meeting",
    description: "Time: 15:10",
  },
  {
    id: 4,
    title: "15 May Meeting",
    description: "Time: 03:45",
  },
  {
    id: 5,
    title: "16 May Meeting",
    description: "Time: 5:10",
  },
  {
    id: 6,
    title: "12 May Meeting",
    description: "Time: 15:10",
  },
  {
    id: 7,
    title: "15 May Meeting",
    description: "Time: 03:45",
  },
  {
    id: 8,
    title: "16 May Meeting",
    description: "Time: 5:10",
  },
  {
    id: 9,
    title: "17 May Meeting",
    description: "Time: 12:10",
  },
  {
    id: 10,
    title: "19 May Meeting",
    description: "Time: 01:45",
  },
  {
    id: 11,
    title: "22 May Meeting",
    description: "Time: 15:10",
  },
  {
    id: 12,
    title: "25 May Meeting",
    description: "Time: 13:10",
  },
  {
    id: 13,
    title: "26 May Meeting",
    description: "Time: 03:20",
  },
  {
    id: 14,
    title: "29 May Meeting",
    description: "Time: 12:10",
  },
  {
    id: 15,
    title: "30 May Meeting",
    description: "Time: 13:10",
  },
];

export default MEETINGS_DATA;
